require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'uct_mobapp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'react-native-image-base64', :path => '../node_modules/react-native-image-base64'

  pod 'react-native-version-info', :path => '../node_modules/react-native-version-info'

  pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'

  target 'uct_mobappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'uct_mobapp-tvOS' do
  # Pods for uct_mobapp-tvOS

  target 'uct_mobapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
